### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by eftekhariyan** [KenLauLab/dropkick#11]
![Screen Shot 2022-10-20 at 12 24 05 pm](https://user-images.githubusercontent.com/47078846/196834463-3017a12a-01c0-4112-84a5-1e0b534204e0.png)

**Comment by eftekhariyan** [comment]
problem solved! just restarted my Mac and now it is working!!

**Comment by codyheiser** [comment]
@eftekhariyan, great!  Thank you for the update!
